using System;
using System.Collections.Generic;
using System.Text;

namespace WinApi.Hid.Usage
{
    /// <summary>
    /// Usages for BatterySystem usage page (133).
    /// </summary>
    /// <remarks>
    /// https://www.freebsddiary.org/APC/usb_hid_usages.php
    /// </remarks>
    public enum BatterySystem
    {
        Undefined = 0x00,
        SMBBatteryMode = 0x01,
        SMBBatteryStatus = 0x02,
        SMBAlarmWarning = 0x03,
        SMBChargerMode = 0x04,
        SMBChargerStatus = 0x05,
        SMBChargerSpecInfo = 0x06,
        SMBSelectorState = 0x07,
        SMBSelectorPreset = 0x08,
        SMBSelectorInfo = 0x09,
        OptionalMfgFunction1 = 0x10,
        OptionalMfgFunction2 = 0x11,
        OptionalMfgFunction3 = 0x12,
        OptionalMfgFunction4 = 0x13,
        OptionalMfgFunction5 = 0x14,
        ConnectionToSMBus = 0x15,
        OutputConnection = 0x16,
        ChargerConnection = 0x17,
        BatteryInsertion = 0x18,
        Usenext = 0x19,
        OKToUse = 0x1A,
        ManufacturerAccess = 0x28,
        RemainingCapacityLimit = 0x29,
        RemainingTimeLimit = 0x2A,
        AtRate = 0x2B,
        CapacityMode = 0x2C,
        BroadcastToCharger = 0x2D,
        PrimaryBattery = 0x2E,
        ChargeController = 0x2F,
        TerminateCharge = 0x40,
        TermminateDischarge = 0x41,
        BelowRemainingCapacityLimit = 0x42,
        RemainingTimeLimitExpired = 0x43,
        Charging = 0x44,
        Discharging = 0x45,
        FullyCharged = 0x46,
        FullyDischarged = 0x47,
        ConditionningFlag = 0x48,
        AtRateOK = 0x49,
        SMBErrorCode = 0x4A,
        NeedReplacement = 0x4B,
        AtRateTimeToFull = 0x60,
        AtRateTimeToEmpty = 0x61,
        AverageCurrent = 0x62,
        Maxerror = 0x63,
        RelativeStateOfCharge = 0x64,
        AbsoluteStateOfCharge = 0x65,
        RemainingCapacity = 0x66,
        FullChargeCapacity = 0x67,
        RunTimeToEmpty = 0x68,
        AverageTimeToEmpty = 0x69,
        AverageTimeToFull = 0x6A,
        CycleCount = 0x6B,
        BattPackModelLevel = 0x80,
        InternalChargeController = 0x81,
        PrimaryBatterySupport = 0x82,
        DesignCapacity = 0x83,
        SpecificationInfo = 0x84,
        ManufacturerDate = 0x85,
        SerialNumber = 0x86,
        iManufacturerName = 0x87,
        iDevicename = 0x88,
        iDeviceChemistery = 0x89,
        iManufacturerData = 0x8A,
        Rechargeable = 0x8B,
        WarningCapacityLimit = 0x8C,
        CapacityGranularity1 = 0x8D,
        CapacityGranularity2 = 0x8E,
        InhibitCharge = 0xC0,
        EnablePolling = 0xC1,
        ResetToZero = 0xC2,
        ACPresent = 0xD0,
        BatteryPresent = 0xD1,
        PowerFail = 0xD2,
        AlarmInhibited = 0xD3,
        ThermistorUnderRange = 0xD4,
        ThermistorHot = 0xD5,
        ThermistorCold = 0xD6,
        ThermistorOverRange = 0xD7,
        VoltageOutOfRange = 0xD8,
        CurrentOutOfRange = 0xD9,
        CurrentNotRegulated = 0xDA,
        VoltageNotRegulated = 0xDB,
        MasterMode = 0xDC,
        ChargerBatteryHostControlled = 0xDD,
        ChargerSpecInfo = 0xF0,
        ChargerSpecRef = 0xF1,
        Level2 = 0xF2,
        Level3 = 0xF3,
    }
}
